### ISSUE TITLE
Validator signatures need to be checked on Fusenet, not Mainnet

### ISSUE THREAD

**Issue by CrackerHax** [fuseio/fuse-bridge#20]
When mainnet has to go through an array of signatures for each bridge transfer it adds to mainnet gas prices. How about we do this on the fuse side where gas is much cheaper so we only need 1 single signature mainnet side? Mainnet doesnt even need to know we have validators at all, all it needs is permission from fusenet to send tokens. No need to pay $12 in eth to transfer 1 fuse token.

**Comment by LiorRabin** [comment]
https://github.com/fuseio/FIPs/issues/8

**Comment by leonprou** [comment]
Closing this as this fixing here https://github.com/fuseio/fuse-bridge/pull/37
