### ISSUE TITLE
Which gas to use when gas price oracle is down

### ISSUE THREAD

**Issue by LiorRabin** [fuseio/fuse-bridge#21]
If the `FOREIGN_GAS_PRICE_ORACLE_URL` is down for some reason, the gas price default to the value from the `.env` file.
Need to think of which options are better:
1. Use a 2nd gas price oracle for fallback
2. Save the latest gas price in Redis and use this value as a fallback. Only if this doesn't exist use the default one from the `.env` file.

**Comment by leonprou** [comment]
Solved by adding a secondary price here https://github.com/fuseio/fuse-bridge/pull/23
