### ISSUE TITLE
Eth gas station now requires an API key

### ISSUE THREAD

**Issue by Andrew-Pohl** [fuseio/fuse-bridge#30]
As of a few weeks ago eth gas station now require an API key to use. This is free up to 1000 calls per day and you have to pay after that. As a result we are hitting the 3rd fall back everytime (the default in the env file) since the validators and the new fuse workaround all fail due to no key. We probably need to look into otherways of getting the gas price. We could use the eth nodes or another service.

**Comment by leonprou** [comment]
I would suggest the following solution
- add the eth gas station's API key param to the  `send-home` container, so it could be configured by the validator in the `.env` file.
- Now the gasPrice is polled any X seconds. I prefer to add another mode of operation, where the gas price can be fetched when needed (before the tx is sent). This can be configured via  the `.env` file as well. Using this mode, you should be able to use the gasstation with a free account.

**Comment by Andrew-Pohl** [comment]
Good news ethgasstations API is currently free to use with an API key https://docs.defipulse.com/api-docs-by-provider/egs

Currently we grab the gas price every 10mins (600 seconds). I will add a new mechanism like Leon said which grabs gas price only on calls to getPrice (), and disable the call to setIntervalAndRun (which grabs gas every 10mins by default). Will sort that this week :)

**Comment by Andrew-Pohl** [comment]
Added a configurable gas price oracle here https://github.com/fuseio/fuse-network/pull/65

@leonprou I can change the the bridge code to only pull when needed (let me know)

**Comment by Andrew-Pohl** [comment]
Only needed to make changes to the QS in the end. The operator can set  FOREIGN_GAS_PRICE_ORACLE_URL in there .env file the quickstart will then check that the format matches that of an ethgas station API. If it doesn't or hasn't been supplied fall back to the old mechanism and display a warning on exit of the quickstart. 

merged at commit 33788619651574fbabc6e273c9715e776ae10b52
